// Plugin Path: ./src/plugins/variant-prefill-plugin/admin/src/components/Initializer/index.js

import { useEffect, useRef } from 'react';
import { useCMEditViewDataManager } from '@strapi/helper-plugin';

const autofillFields = [
  'price',
  'compare_at_price',
  'reorder_level',
  'restock_date',
  'warehouse_location',
  'backorder_allowed',
  'inventory_status',
  'stock_quantity',
];

const hiddenAutoFields = [
  'base_sku',
  'product_code',
  'factory_batch_code',
  'label_serial_code',
  'tag_serial_code',
  'barcode',
];

const Initializer = () => {
  const { modifiedData, updateModifiedData, layout } = useCMEditViewDataManager();
  const lastFilledRef = useRef({});

  useEffect(() => {
    if (!modifiedData?.product_variant) return;

    modifiedData.product_variant.forEach((variant, variantIndex) => {
      variant?.sizes?.forEach((size, sizeIndex) => {
        autofillFields.forEach((field) => {
          if (!size[field] && lastFilledRef.current[field]) {
            updateModifiedData({
              keys: [`product_variant[${variantIndex}].sizes[${sizeIndex}].${field}`],
              value: lastFilledRef.current[field],
            });
          }
        });
        // Update last filled values
        autofillFields.forEach((field) => {
          if (size[field]) lastFilledRef.current[field] = size[field];
        });
        // Auto-copy stock_quantity to inventory_count
        if (!size.inventory_count && size.stock_quantity) {
          updateModifiedData({
            keys: [`product_variant[${variantIndex}].sizes[${sizeIndex}].inventory_count`],
            value: size.stock_quantity,
          });
        }
      });
    });
  }, [modifiedData]);

  useEffect(() => {
    // Hide autogenerated fields visually
    if (layout && layout.contentType) {
      layout.contentType.layouts.edit = layout.contentType.layouts.edit.filter(
        (section) =>
          !section.some((field) => hiddenAutoFields.includes(field.name))
      );
    }
  }, [layout]);

  return null;
};

export default Initializer;
